_map = [[['-inf', 'inf', 1, 'inf', '-inf', 'inf'], ['inf', 'inf', 0, 0, 'inf', 'inf'], ['inf', 'inf', 0, 'inf', 0, 'inf'], ['inf', 'inf', 'inf', 0, 0, 'inf']],
        [['inf', 'inf', 'inf', 1, 0, 1], ['inf', 0, 0, 'inf', 'inf', 'inf'], ['inf', 0, 'inf', 'inf', 'inf', 0], ['inf', 'inf', 'inf', 0, 0, 'inf']],
        [['inf', 0, 0, 'inf', 'inf', 'inf'], [0, 'inf', 'inf', 'inf', 'inf', 'inf'], ['inf', 'inf', 'inf', 'inf', 0, 0], [0, 0, 'inf', 'inf', 'inf', 'inf']],
        [['inf', 'inf', 0, 'inf', 'inf', 0], ['inf', 0, 0, 'inf', 'inf', 'inf'], ['inf', 'inf', 0, 'inf', 0, 'inf'], [0, 'inf', 'inf', 0, 'inf', 'inf']],
        [['inf', 'inf', 0, 0, 'inf', 'inf'], ['inf', 'inf', 'inf', 'inf', 0, 0], ['inf', 0, 'inf', 'inf', 'inf', 0], ['inf', 'inf', 'inf', 0, 'inf', 0]],
        [['inf', 0, 'inf', 'inf', 'inf', 0], ['inf', 'inf', 0, 'inf', 0, 'inf'], ['inf', 'inf', 0, 0, 'inf', 'inf'], [0, 'inf', 'inf', 0, 'inf', 'inf']],
        [[0, 'inf', 0, 0, 'inf', 'inf'], ['inf', 0, 'inf', 'inf', 0, 'inf'], ['inf', 'inf', 'inf', 0, 'inf', 0], [0, 'inf', 'inf', 'inf', 'inf', 0]],
        [['inf', 0, 'inf', 'inf', 'inf', 0], ['inf', 'inf', 'inf', 0, 0, 'inf'], [0, 'inf', 'inf', 0, 'inf', 'inf'], [0, 'inf', 'inf', 'inf', 0, 'inf']],
        [[0, 'inf', 0, 'inf', 'inf', 'inf'], ['inf', 0, 'inf', 'inf', 'inf', 'inf'], [0, 'inf', 0, 'inf', 'inf', 'inf'], ['inf', 0, 0, 'inf', 'inf', 'inf']],
        [['inf', 'inf', 'inf', 'inf', 0, 0], [0, 'inf', 'inf', 0, 'inf', 'inf'], [0, 'inf', 0, 'inf', 'inf', 0], ['inf', 'inf', 'inf', 0, 'inf', 0]],
        [['inf', 0, 'inf', 0, 'inf', 'inf'], ['inf', 'inf', 'inf', 0, 0, 'inf'], ['inf', 'inf', 0, 0, 'inf', 'inf'], ['inf', 'inf', 'inf', 'inf', 0, 0]],
        [['inf', 0, 'inf', 'inf', 0, 'inf'], [0, 'inf', 'inf', 'inf', 0, 'inf'], ['inf', 0, 'inf', 'inf', 'inf', 0], [0, 'inf', 'inf', 'inf', 0, 'inf']],
        [[0, 0, 'inf', 'inf', 'inf', 'inf'], [0, 0, 'inf', 'inf', 'inf', 'inf'], [0, 'inf', 'inf', 'inf', 'inf', 'inf'], ['inf', 0, 'inf', '-inf', 'inf', 'inf']]]
